create table "aluno"
(
    id           int generated by Default as identity,
    senha        varchar(16) not null,
    cpf          varchar(11) not null,
    nome         varchar(70) not null,
    dt_nascimento date,-- Mudar para not null

    CONSTRAINT pk_aluno PRIMARY KEY (id),
    CONSTRAINT uk_aluno_cpf UNIQUE (cpf)
);

create table "plano"(
    id           int generated by Default as identity,
    nome         varchar(75) not null,
    ativo        BOOLEAN not null,

    CONSTRAINT pk_plano PRIMARY KEY (id)
);

create table "beneficio"(
    id           int generated by Default as identity,
    descricao    varchar(1024) not null,
    plano_id     int not null,

    CONSTRAINT pk_beneficios PRIMARY KEY (id),
    CONSTRAINT fk_beneficio_plano FOREIGN KEY (plano_id) references plano(id)
);

create table "contrato"(
    id           int generated  by DEFAULT as identity,
    vigencia     int not null,
    vigencia_unidade smallint not null,
    dt_inicio    timestamp with time zone not null default current_timestamp,
    dt_final     date,
    ativo        BOOLEAN,
    valor        numeric(10,2) not null,
    aluno_id     int NOT NULL,
    plano_id     int NOT NULL,

    CONSTRAINT pk_contrato PRIMARY KEY (id),
    CONSTRAINT fk_contrato_aluno FOREIGN KEY (aluno_id) REFERENCES aluno(id),
    CONSTRAINT fk_contrato_plano FOREIGN KEY (plano_id) REFERENCES plano(id)
);